### ISSUE TITLE
Language Server: Initial feature requirements

### ISSUE THREAD

**Issue by KwilLuke** [kwilteam/kuneiform-ls#1]
Some initial features come to mind...

- [ ] Syntax highlighting for all Kuneiform keywords, SQL keywords (and discriminately applying highlighting based on keywords, such that SQL keywords are only highlighted within procedures/actions, words like "public" and "view" are only highlighted in action/procedure signature, etc), and variable types (string, boolean, number).
     - The current keywords i track in DB admin can be found here; however, feel free to double check against the docs. These may not be exhaustive: [SQL keywords](https://github.com/kwilteam/db-admin/blob/main/lib/kuneiform/kfLanguage.ts) & [Kuneiform keywords](https://github.com/kwilteam/db-admin/blob/main/lib/kuneiform/sqlKeywords.ts).
     - The highlighting I currently use [is here](https://github.com/kwilteam/db-admin/blob/be24b9807ae045671280680583dc826854a42b1f/lib/kuneiform/kfLanguage.ts#L278), however, feel free to propose other highlighting options.

- [ ] Auto closing brackets and strings (e.g. when i type "{", it autocompletes the "}". And if I type "}" right before the autocompleted "}" it skips over it rather than adding a new curly bracket). For the monaco editor, this is a setting that is configurable - I imagine it is similarily simple with the language server?
- [ ] Context aware autocomplete for (1) tables; (2) actions; (3) procedures; (4) action/procedure parameters. "Context aware" means that autocomplete show up when they are syntactically allowed, but not when they are not. A few examples that come to mind:
     - Actions can call other procedures and actions; however, procedures can only call other procedures. So autocompleted actions should not show up when you are within a procedure block.
     - Action / procedure parameters should only appear within the procedure block that they are defined. For example, the parameters on `procedure do_something($x1, $x2)` should only be show up within `procedure do_something()`.

@brennanjl @charithabandi any other ideas?

**Comment by brennanjl** [comment]
These all sound great to me. Honestly all I really had in mind was syntax highlighting and validation, but I do agree that these features would be really useful to people building with Kuneiform.

**Comment by KwilLuke** [comment]
@charithabandi feel free to close this issue if all of the points are addressed.
