### ISSUE TITLE
Bug: Precompile Import Syntax Highlighting

### ISSUE THREAD

**Issue by brennanjl** [kwilteam/kuneiform-ls#11]
There seems to be inconsistent highlighting when using precompiles.

First, it does not properly highlight strings in the configuration:

```
database timescale;

use timescaledb {
    weather: 'temp'
} as timescale;
```

The `temp` string is not highlighted.

Second, initializing an extension without a config highlights differently than with a config:

```
database timescale;

use timescaledb  as timescale;
```

**Comment by charithabandi** [comment]
Fixed 
![Screenshot 2024-09-19 at 11 45 05 AM](https://github.com/user-attachments/assets/643ab3a0-d72f-4ded-af58-25ebfe76304c)
