### ISSUE TITLE
Support for recent changes/upgrades to Kuneiform

### ISSUE THREAD

**Issue by notxorand** [kwilteam/kuneiform-ls#12]
There's currently no support for the syntax changes in the recent update made to Kwil @ [https://github.com/kwilteam/kwil-db/blob/main/docs/release-notes/release-v0.9.md](https://github.com/kwilteam/kwil-db/blob/main/docs/release-notes/release-v0.9.md).

Among those includes variables such as `@block_timestamp`, `@foreign_caller`, `@authenticator`, as well as others which can be found @ [#kuneiform-additions](https://github.com/kwilteam/kwil-db/blob/main/docs/release-notes/release-v0.9.md#kuneiform-additions).

**Comment by brennanjl** [comment]
Ah thanks for flagging.

CC @charithabandi Could you update this and re-release the extension?

**Comment by charithabandi** [comment]
Added support to all the things listed here [#kuneiform-additions](https://github.com/kwilteam/kwil-db/blob/main/docs/release-notes/release-v0.9.md#kuneiform-additions)
