### ISSUE TITLE
Language server v0.0.1 feedback

### ISSUE THREAD

**Issue by KwilLuke** [kwilteam/kuneiform-ls#3]
This is some initial feedback. I am sure there are more things, but this is what immediately jumps out.

LMK if any questions.

### Feature
- [x] Is there a specific reason the column modifier `primary` has a different color than the other column modifiers (e.g. `notnull`, `max`, `unique`, etc. If there is no reason, I suggest all modifiers have the same color.
- [x] Add autocomplete for contextual variables, when autocomplete is appropriate (within action and procedure blocks): https://docs.kwil.com/docs/kuneiform/introduction#contextual-variables.
- [x] Add syntax highlighting for index values. E.g. 
![Screen Shot 2024-06-25 at 5 41 27 PM](https://github.com/kwilteam/kuneiform-ls/assets/105600466/af8aac59-ec6e-40d7-8f4b-ac6434f3e35e)
- [ ] IMO, we should remove autocomplete for SQL keywords. It leads to a lot of suggestions when typing actions/procedures. @brennanjl @charithabandi thoughts?

### Bugs / UX Feedback
- [x] If i define a database, delete the database, then start typing `da...` I no longer get the `database` autocomplete. I only get the `tables`, `actions`, and `procedures`. It should revert to recommending `database`.
- [x] Keywords do not highlight until after the syntax is complete, however, they should highlight immediately if defined in a location where the keyword is acceptable. For example, if i type `database mydb`, there is no highlighting. But if i type `database mydb;`, highlighting applies to both `database` and `mydb`. This also applies to tables, actions, and procedures.
- [ ] Within the table block, I receive autocompletes for procedures and actions. It looks like this is caused because, upon first defintion, the parser does not realize we are within a valid table block. Example: 
![image](https://github.com/kwilteam/kuneiform-ls/assets/105600466/d1e315ef-178f-4c2e-986d-b3d3ac2c9b75)
- [ ] If I define a table, then delete the table and try to define again, i lose the table autocomple. E.g. start here: 
![image](https://github.com/kwilteam/kuneiform-ls/assets/105600466/dc34b901-37de-4c41-86cd-54d48c33a80d) then delete and start a new table: 
![image](https://github.com/kwilteam/kuneiform-ls/assets/105600466/d7618dab-678b-42ad-8472-39e984c8a423)
- [x] The red on table in `return table` is a bit jarring and looks like an error. Maybe a more subtle blue (like the same color used in the table definition) would be better? E.g.
![image](https://github.com/kwilteam/kuneiform-ls/assets/105600466/47f5e7f8-f450-4e5e-ada9-05dcc78cee8e)
 - [x] If I type a `$` and then select the autocomplete param, it inserts an extra $. Start here: 
![image](https://github.com/kwilteam/kuneiform-ls/assets/105600466/0d9794f2-ef4f-402c-8c79-bba47cfe80f6) leads to this: 
![image](https://github.com/kwilteam/kuneiform-ls/assets/105600466/a5d704c2-c9b1-4713-87a5-20105c36aa60)

**Comment by charithabandi** [comment]
Fixed all of the issues, except auto-completion, that requires changes from the kwil-db parse module.
