### ISSUE TITLE
Feedback: Kuneiform LS v0.0.1

### ISSUE THREAD

**Issue by KwilLuke** [kwilteam/kuneiform-ls#6]
More feedback. I can help with these, too:

- [x] The `database` autocomplete has a weird curly bracket (e.g. `database {}`). This is weird because the database declaration does not use curly brackets. I would probably just have it be something like: `database ${1:};`
- [x] `decimal()` does not have syntax highlighting. See image: 
![image](https://github.com/user-attachments/assets/0a629468-33fb-40ec-99ca-58b169c4167d)
- [x] I think the sole `decimal` autocomplete is unnecessary. All decimals will need a precision specified, so it will never be just `decimal`.
![image](https://github.com/user-attachments/assets/f347a276-5b80-4ba8-b027-04cc65df8636)
- [x] Add syntax highlighting for built-in functions (e.g., `uuid_generate_v5()` and `encode()`), probably the same color as actions and procedures. 
![image](https://github.com/user-attachments/assets/6e96ee54-d448-40eb-a9f5-37281d43ff3b)
- [x] Add syntax highlighting for the `@kgw` annotation: 
![image](https://github.com/user-attachments/assets/b13a7cd9-c69c-4266-97b7-7ef24be6a389)
- [x] Make the syntax highlighting for contextual variables for differentiation. Something purplish/pinkish might be good. 
![image](https://github.com/user-attachments/assets/478bf6ad-4488-4229-ad53-df94e1249713)
- [ ] #7
![image](https://github.com/user-attachments/assets/4b20acaf-601f-4a1a-a1e6-25f69799e9cb)
- [ ] #8
![image](https://github.com/user-attachments/assets/c4b021ce-d8b0-4372-a470-a6ff619887c0)
- [x] Add syntax highlighting for integers. Like a light green or smthn: 
![image](https://github.com/user-attachments/assets/ce591cc6-6e69-4d4b-849a-5ed3b28fcacf)

**Comment by charithabandi** [comment]
<img width="316" alt="Screenshot 2024-07-16 at 3 42 56 PM" src="https://github.com/user-attachments/assets/0862ffdb-9ede-4dc6-b350-15a0724e3a6e">
 Weird, decimal is highlighted in mine.

**Comment by KwilLuke** [comment]
I will create backburner issues for the two items we decided not to work on.
